# 访问端口
server:
  port: 8887
# 数据源
spring:
  datasource:
    username: # 数据库账户名
    password: # 数据库密码
    url: jdbc:mysql://localhost/zykt?useSSL=FALSE&serverTimezone=UTC&characterEncoding=utf-8&noaccesstoprocedureboodies=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2.0版本需要做处理
    initialization-mode: always
  # redis缓存 spring.redis.host=192.168.0.108
  redis:
    # redis服务器主机地址（虚拟机地址）
    host: 192.168.43.192
    # redis数据库索引使用（默认为0）
    database: 1
    # 访问端口
    port: 6379
    # 密码
    password: # 密码
    # 连接池最大数
    jedis:
      pool:
        # 最大连接数
        max-active: 1000
        # 最大阻塞等待时间
        max-wait: -1ms
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 2
  cache:
    type: redis
# mybatis配置
mybatis:
  type-aliases-package: com.wd.zykt.pojo
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


# token令牌密钥
zykt:
  com:
    wxAppid: # 微信appid
    wxSecretKey: # 微信密钥
    qqAppid: # qq appid
    qqSecretKey:  # qq 密钥
    fileSpace:  # 访问文件目录
    tokenSecret: # token
    # AES 密钥
    aesSecret: # aes 加密